---
chapter: अध्याय १२
pageNumber: ६९
titleIndex: १२.१
---
# अध्याय १२
# त्रुटि ह्यान्डलिंग

प्रोग्रामिंग त्रुटिहरूमा विभिन्न कारणहरूको लागि हुन्छ, केहि कोड त्रुटिहरूबाट हुन्छन्, केहि गलत इनपुटको कारण, र अन्य अप्रत्याशित चीजहरूको कारण।  जब एउटा त्रुटि हुन्छ, कोड रोकिन्छ र सामान्यतया कन्सोलमा देखिने त्रुटि सन्देश उत्पन्न गर्दछ ।

# प्रयास ... क्याच

कोड कार्यान्वयन रोक्नुको सट्टा, हामी `प्रयास गर्नुहोस् ... क्याच` निर्माण जसले स्क्रिप्टको मृत्यु बिना त्रुटिहरू समात्न अनुमति दिन्छ। 'कोशिश... क्याच 'कन्स्ट्रक्टमा दुई मुख्य ब्लकहरू छन्; 'कोशिश' और फिर 'कैच'।

```javascript
try {
  // code...
} catch (err) {
  // error handling
}
```

सुरुमा, `प्रयास` ब्लकमा कोड कार्यान्वयन गरिन्छ। यदि कुनै त्रुटिहरू देखा परेनन् भने यसले `क्याच` ब्लक छोड्छ। यदि कुनै त्रुटि उत्पन्न हुन्छ भने `प्रयास` कार्यान्वयन रोकिन्छ, नियन्त्रण अनुक्रमलाई `क्याच` ब्लकमा सार्दछ। त्रुटिको कारण `त्रुटि` चरमा कब्जा गरिएको छ।

```javascript
try {
  // code...
  alert('Welcome to Learn JavaScript');  
  asdk; // error asdk variable is not defined
} catch (err) {
  console.log("Error has occurred");
}
```

{% hint style="warning" %}

`प्रयास ... क्याच` रनटाइम त्रुटिहरूको लागि काम गर्दछ जसको अर्थ कोड रनेबल र सिंक्रोनस हुनुपर्दछ।
{% endhint %}

अनुकूल त्रुटि फ्याँक्न, 'थ्रो' कथन प्रयोग गर्न सकिन्छ। त्रुटि वस्तु, जुन त्रुटिहरू द्वारा उत्पन्न हुन्छ, दुई मुख्य गुणहरू छन्।

* **नाम**: त्रुटि नाम
* **सन्देश**: त्रुटिको बारेमा विवरण

{% hint style="info" %}

यदि हामीलाई 'त्रुटि' सन्देश आवश्यक छैन भने क्याचले यसलाई छोड्न सक्छ।
{% endhint %}
